"""fix password reset otp fields

Revision ID: 215788c0fb8b
Revises: 211567de2b6b
Create Date: 2026-09-01 01:04:49.664069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '215788c0fb8b'
down_revision: Union[str, Sequence[str], None] = '211567de2b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_otps', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('password_reset_otps', 'otp',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('password_reset_otps', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('password_reset_otps', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_password_reset_otps_id'), 'password_reset_otps', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_otps_user_id'), 'password_reset_otps', ['user_id'], unique=False)
    op.drop_constraint(op.f('password_reset_otps_user_id_fkey'), 'password_reset_otps', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_otps', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'password_reset_otps', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_otps_user_id_fkey'), 'password_reset_otps', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_password_reset_otps_user_id'), table_name='password_reset_otps')
    op.drop_index(op.f('ix_password_reset_otps_id'), table_name='password_reset_otps')
    op.alter_column('password_reset_otps', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('password_reset_otps', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('password_reset_otps', 'otp',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('password_reset_otps', 'created_at')
    # ### end Alembic commands ###
