"""add unique company slug to jobs

Revision ID: a6c5bb0a3a45
Revises: b46f7534a51a
Create Date: 2026-09-03 11:04:07.787238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c5bb0a3a45'
down_revision: Union[str, Sequence[str], None] = 'b46f7534a51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_job_company_slug', 'jobs', ['company_id', 'slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_company_slug', 'jobs', type_='unique')
    # ### end Alembic commands ###
