"""add employer request and unique employer id

Revision ID: b46f7534a51a
Revises: 3c0d393b0b71
Create Date: 2026-09-03 07:19:39.341205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46f7534a51a'
down_revision: Union[str, Sequence[str], None] = '3c0d393b0b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='employerrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_requests_id'), 'employer_requests', ['id'], unique=False)
    op.create_index(op.f('ix_employer_requests_user_id'), 'employer_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_companies_employer_id'), 'companies', ['employer_id'], unique=True)
    op.drop_constraint(op.f('companies_employer_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['employer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_employer_id_fkey'), 'companies', 'users', ['employer_id'], ['id'])
    op.drop_index(op.f('ix_companies_employer_id'), table_name='companies')
    op.drop_index(op.f('ix_employer_requests_user_id'), table_name='employer_requests')
    op.drop_index(op.f('ix_employer_requests_id'), table_name='employer_requests')
    op.drop_table('employer_requests')
    # ### end Alembic commands ###
